language: node_js

node_js:
  - "6.10.3"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

script: make test && make coverage && make coveralls || true
